### PR TITLE
67 copy tweaks to academy login page

### PR DESCRIPTION
**Pull request by thulshof**
Implemented copy changes as requested in https://github.com/Yoast/yoast.academy/issues/67

Fixes https://github.com/Yoast/yoast.academy/issues/67

### CODE REVIEW

**Comment by maartenleenders** [comment]
CR 👍

**Comment by maartenleenders** [comment]
@JesseYoast Before I commit, a question about the copy: 
the link `Yoast SEO for WordPress plugin course` goes to `Yoast SEO for WordPress training`, so I guess we can/should drop the word _plugin_?

Also, I find the capitalized B in the `Basic SEO` link, and the capitalized C in the `Courses page` link a bit weird. Could be made lowercase?

**Comment by JesseYoast** [comment]
Thumbs up on both, thanks for thinking along!

**Comment by maartenleenders** [comment]
Acceptance 👍

**Pull request merged**
