### PR TITLE
Fixed nesting for site header and navigation header

### PR DESCRIPTION
**Pull request by RobinvanderVliet**
Related to: https://github.com/Yoast/yoast.academy/pull/122

### CODE REVIEW

**Comment by diedexx** [comment]
@Sjardo can you do a quick review?

**Comment by Sjardo** [comment]
cr 👍

**Comment by diedexx** [comment]
these changes shouuld also be applied on the yoast-theme dir in the yoast.com repo

**Comment by Sjardo** [comment]
No longer relevant

**Pull request closed without merging**
